language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t johnchristofis/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true johnchristofis/docker-react npm run test